### ISSUE TITLE
some questions about 990_2nd_place_solution_golf

### ISSUE THREAD

**Issue by Edogawa-Konan** [KazukiOnodera/Santander-Customer-Transaction-Prediction#1]
hello，I found a problem when I looked at your code.
`# =============================================================================
# stratified
# =============================================================================
train_group = np.arange(len(X_train_concat))%200000

id_y = pd.DataFrame(zip(train_group, y_train_concat), 
                    columns=['id', 'y'])

id_y_uq = id_y.drop_duplicates('id').reset_index(drop=True)`

I think the last sentence seems to be meaningless. 
Because `id_y_uq.equals(id_y[:200000])` return true.
Is it what I ignored?
I look forward to your reply. Thank you.

**Comment by KazukiOnodera** [comment]
Same as `id_y_uq.equals(id_y[:200000])`, but readable. And `id_y_uq` is used in https://github.com/KazukiOnodera/Santander-Customer-Transaction-Prediction/blob/master/py/990_2nd_place_solution_golf.py#L177-L178
